### ISSUE TITLE
Users asking the bot to remember additional things about them overwrites previously saved information.

### ISSUE THREAD

**Issue by tanneryould** [RapidRabbit-11485/PNGTuber-GPT#26]
I had a user trying to teach the bot multiple things about themselves, but the bot would only remember the last thing saved. I manually updated their key value `keyword_contexts.json` to a string of all their responses separated by semicolons. In the future it may be worthwhile to make the values an array of strings, but as a quick fix, appending a semicolon and the new information to the end of the current value seems to work sufficiently.
https://github.com/RapidRabbit-11485/PNGTuber-GPT/blob/09f541d6555b8abb96874cbcb60a881e28047a81/GPT.cs#L1638

**Comment by RapidRabbit-11485** [comment]
There's a specific reason *not* to do this. The feature was not built with the ability to remember multiple things about the person. Rather they are supposed to fill that with as many things as they want in a single response. If you look at the code what this does is literally take that string and form it into a sentence: I remember x about x when it's dynamically forming the context. There are multiple reasons for this:

1) A text file is not a database. Even having to expand or search within strings in a database is not conducive to low-latency performance. It's not scalable at all. In fact, SQL isn't even enough for the kind of context that people want, we invented a new type of database for AI that uses contextual embeddings, called a Vector Database. This allows AI to quickly remember things about individuals, up to pages of information or even documents. The problem is that won't run on your typical gaming PC, it's built to run in a datacenter, or with Docker and a lot of technical expertise. This is built to be a fun little toy.

2) This increases the context size dramatically that is being sent, not only would be doing array expansion and processing of what is actually related to the user's query or not, but this is just a bunch of unrelated text that may have nothing to do with the user's query. It just confuses it, and in our testing makes the bot care more about those things than what the bot is actually being asked. We can't feed the bot 1,000 lines of text, and then ask a 5 word question and expect it to care more about 5 whole words. This is exacerbated when using small models like gpt-3.5-turbo, where you can even break it to not give a response at all because you send too much context.

3) The solution is modular, do what you want with it. I'm trying to explain the reasons it was developed in this manner. And also how you may break it by not understanding how it actually works.

**Comment by RapidRabbit-11485** [comment]
There's a specific reason *not* to do this. The feature was not built with the ability to remember multiple things about the person. Rather they are supposed to fill that with as many things as they want in a single response. If you look at the code what this does is literally take that string and form it into a sentence: I remember x about x when it's dynamically forming the context. There are multiple reasons for this:

1) A text file is not a database. Even having to expand or search within strings in a database is not conducive to low-latency performance. It's not scalable at all. In fact, SQL isn't even enough for the kind of context that people want, we invented a new type of database for AI that uses contextual embeddings, called a Vector Database. This allows AI to quickly remember things about individuals, up to pages of information or even documents. The problem is that won't run on your typical gaming PC, it's built to run in a datacenter, or with Docker and a lot of technical expertise. This is built to be a fun little toy.

2) This increases the context size dramatically that is being sent, not only would be doing array expansion and processing of what is actually related to the user's query or not, but this is just a bunch of unrelated text that may have nothing to do with the user's query. It just confuses it, and in our testing makes the bot care more about those things than what the bot is actually being asked. We can't feed the bot 1,000 lines of text, and then ask a 5 word question and expect it to care more about 5 whole words. This is exercerbated when using small models like gpt-3.5-turbo, where you can even break it to not give a response at all because you send too much context.

**Comment by RapidRabbit-11485** [comment]
Also consider, if you build it into an array of strings. You have build some kind of management system for them to delete a specific one and not the others. That's a nightmare.

**Comment by tanneryould** [comment]
Hm, okay, I see your point and yeah, this is significantly more complex than I had originally assumed. I'll ensure my redeem properly documents this so that people aren't overwriting info with additional things, thanks!

**Comment by RapidRabbit-11485** [comment]
I've considered going the database route, it's just a lot. I have to ask for 8GB of RAM at minimum, and the solution wouldn't run on Streamer.bot anymore, because it can't load the DLLs needed to run with a full SQL server. We've tried it and it's just asking too much of it. I may build a commercial solution for this one day; but I really don't think there is the demand to satisfy the hundreds of hours of coding it would require, nor do I today have that kind of talent to take on myself. I realize there aren't a lot of better solutions in the market today, and mine does a lot of cool stuff - but it's kind of a toy I made in my spare time and shared with others. A lot of people find fun with it. That's why I have kept it around and maintained. However, the future for this is still pretty unclear.

**Comment by tanneryould** [comment]
That's totally fair and you make a lot of good points! For what this is, it's phenomenal and I sincerely appreciate that you've made it so publically accessible.
My main impetus for opening this issue and pr was that I just want to help contribute to this project. I don't have a ton of cs experience though (I work in C++ and Qt primarily), so this seemed like a good starting point. I'll continue to play around with it and see if there's anything I can do to help.
